# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eurocam.ui'
#
# Created: Wed Mar 25 01:05:35 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 663)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTab = QtGui.QTabWidget(self.centralwidget)
        self.MainTab.setGeometry(QtCore.QRect(10, 50, 361, 471))
        self.MainTab.setObjectName("MainTab")
        self.ModelTab = QtGui.QWidget()
        self.ModelTab.setObjectName("ModelTab")
        self.MdLName = QtGui.QLabel(self.ModelTab)
        self.MdLName.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.MdLName.setObjectName("MdLName")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.ModelTab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 90, 341, 301))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.MdLmax = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLmax.setAlignment(QtCore.Qt.AlignCenter)
        self.MdLmax.setObjectName("MdLmax")
        self.gridLayout_5.addWidget(self.MdLmax, 0, 2, 1, 1)
        self.MdTmX = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTmX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MdTmX.setObjectName("MdTmX")
        self.gridLayout_5.addWidget(self.MdTmX, 1, 1, 1, 1)
        self.MdTmY = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTmY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MdTmY.setObjectName("MdTmY")
        self.gridLayout_5.addWidget(self.MdTmY, 2, 1, 1, 1)
        self.MdLdh = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLdh.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MdLdh.setText("")
        self.MdLdh.setObjectName("MdLdh")
        self.gridLayout_5.addWidget(self.MdLdh, 0, 0, 1, 1)
        self.MdLZ = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLZ.setObjectName("MdLZ")
        self.gridLayout_5.addWidget(self.MdLZ, 3, 0, 1, 1)
        self.MdLX = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLX.setObjectName("MdLX")
        self.gridLayout_5.addWidget(self.MdLX, 1, 0, 1, 1)
        self.MdLY = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLY.setObjectName("MdLY")
        self.gridLayout_5.addWidget(self.MdLY, 2, 0, 1, 1)
        self.MdTMY = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTMY.setObjectName("MdTMY")
        self.gridLayout_5.addWidget(self.MdTMY, 2, 2, 1, 1)
        self.MdTMX = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTMX.setObjectName("MdTMX")
        self.gridLayout_5.addWidget(self.MdTMX, 1, 2, 1, 1)
        self.MdTMZ = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTMZ.setObjectName("MdTMZ")
        self.gridLayout_5.addWidget(self.MdTMZ, 3, 2, 1, 1)
        self.MdTmZ = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTmZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MdTmZ.setObjectName("MdTmZ")
        self.gridLayout_5.addWidget(self.MdTmZ, 3, 1, 1, 1)
        self.MdLmin = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setItalic(False)
        self.MdLmin.setFont(font)
        self.MdLmin.setAlignment(QtCore.Qt.AlignCenter)
        self.MdLmin.setObjectName("MdLmin")
        self.gridLayout_5.addWidget(self.MdLmin, 0, 1, 1, 1)
        self.MdLdimx = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLdimx.setObjectName("MdLdimx")
        self.gridLayout_5.addWidget(self.MdLdimx, 1, 4, 1, 1)
        self.MdLdimz = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLdimz.setObjectName("MdLdimz")
        self.gridLayout_5.addWidget(self.MdLdimz, 3, 4, 1, 1)
        self.MdLdimy = QtGui.QLabel(self.gridLayoutWidget_4)
        self.MdLdimy.setObjectName("MdLdimy")
        self.gridLayout_5.addWidget(self.MdLdimy, 2, 4, 1, 1)
        self.MdTdimx = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTdimx.setObjectName("MdTdimx")
        self.gridLayout_5.addWidget(self.MdTdimx, 1, 3, 1, 1)
        self.MdTdimy = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTdimy.setObjectName("MdTdimy")
        self.gridLayout_5.addWidget(self.MdTdimy, 2, 3, 1, 1)
        self.MdTdimz = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.MdTdimz.setObjectName("MdTdimz")
        self.gridLayout_5.addWidget(self.MdTdimz, 3, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 3, 1, 1)
        self.MdTName = QtGui.QTextEdit(self.ModelTab)
        self.MdTName.setGeometry(QtCore.QRect(10, 30, 341, 51))
        self.MdTName.setObjectName("MdTName")
        self.MainTab.addTab(self.ModelTab, "")
        self.MachineTab = QtGui.QWidget()
        self.MachineTab.setObjectName("MachineTab")
        self.MachCB = QtGui.QComboBox(self.MachineTab)
        self.MachCB.setGeometry(QtCore.QRect(130, 10, 221, 25))
        self.MachCB.setObjectName("MachCB")
        self.label = QtGui.QLabel(self.MachineTab)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.label.setObjectName("label")
        self.layoutWidget = QtGui.QWidget(self.MachineTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 380, 343, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MachNewPB = QtGui.QPushButton(self.layoutWidget)
        self.MachNewPB.setObjectName("MachNewPB")
        self.horizontalLayout_2.addWidget(self.MachNewPB)
        self.MachModPB = QtGui.QPushButton(self.layoutWidget)
        self.MachModPB.setObjectName("MachModPB")
        self.horizontalLayout_2.addWidget(self.MachModPB)
        self.MachDelPB = QtGui.QPushButton(self.layoutWidget)
        self.MachDelPB.setObjectName("MachDelPB")
        self.horizontalLayout_2.addWidget(self.MachDelPB)
        self.MachConfPB = QtGui.QPushButton(self.MachineTab)
        self.MachConfPB.setGeometry(QtCore.QRect(10, 410, 90, 26))
        self.MachConfPB.setObjectName("MachConfPB")
        self.MachNB = QtGui.QTabWidget(self.MachineTab)
        self.MachNB.setGeometry(QtCore.QRect(0, 30, 361, 341))
        self.MachNB.setObjectName("MachNB")
        self.MGT_1 = QtGui.QWidget()
        self.MGT_1.setObjectName("MGT_1")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.MGT_1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 351, 301))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MGLFX = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MGLFX.setObjectName("MGLFX")
        self.gridLayout_2.addWidget(self.MGLFX, 3, 0, 1, 1)
        self.MGLFY = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MGLFY.setObjectName("MGLFY")
        self.gridLayout_2.addWidget(self.MGLFY, 5, 0, 1, 1)
        self.MGLTX = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MGLTX.setObjectName("MGLTX")
        self.gridLayout_2.addWidget(self.MGLTX, 0, 0, 1, 1)
        self.MGLTY = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MGLTY.setObjectName("MGLTY")
        self.gridLayout_2.addWidget(self.MGLTY, 1, 0, 1, 1)
        self.MGLTZ = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MGLTZ.setObjectName("MGLTZ")
        self.gridLayout_2.addWidget(self.MGLTZ, 2, 0, 1, 1)
        self.MGLFZ = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MGLFZ.setObjectName("MGLFZ")
        self.gridLayout_2.addWidget(self.MGLFZ, 6, 0, 1, 1)
        self.MGCoCB = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.MGCoCB.setObjectName("MGCoCB")
        self.gridLayout_2.addWidget(self.MGCoCB, 7, 1, 1, 1)
        self.MGLCo = QtGui.QLabel(self.gridLayoutWidget_2)
        self.MGLCo.setObjectName("MGLCo")
        self.gridLayout_2.addWidget(self.MGLCo, 7, 0, 1, 1)
        self.MGSPTX = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.MGSPTX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MGSPTX.setObjectName("MGSPTX")
        self.gridLayout_2.addWidget(self.MGSPTX, 0, 1, 1, 1)
        self.MGSPTY = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.MGSPTY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MGSPTY.setObjectName("MGSPTY")
        self.gridLayout_2.addWidget(self.MGSPTY, 1, 1, 1, 1)
        self.MGSPTZ = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.MGSPTZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MGSPTZ.setObjectName("MGSPTZ")
        self.gridLayout_2.addWidget(self.MGSPTZ, 2, 1, 1, 1)
        self.MGSPFX = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.MGSPFX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MGSPFX.setObjectName("MGSPFX")
        self.gridLayout_2.addWidget(self.MGSPFX, 3, 1, 1, 1)
        self.MGSPFY = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.MGSPFY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MGSPFY.setObjectName("MGSPFY")
        self.gridLayout_2.addWidget(self.MGSPFY, 5, 1, 1, 1)
        self.MGSPFZ = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.MGSPFZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MGSPFZ.setObjectName("MGSPFZ")
        self.gridLayout_2.addWidget(self.MGSPFZ, 6, 1, 1, 1)
        self.MachNB.addTab(self.MGT_1, "")
        self.MGT_2 = QtGui.QWidget()
        self.MGT_2.setObjectName("MGT_2")
        self.formLayoutWidget = QtGui.QWidget(self.MGT_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 341, 301))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.MGLnote = QtGui.QLabel(self.formLayoutWidget)
        self.MGLnote.setObjectName("MGLnote")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.MGLnote)
        self.MGTnote = QtGui.QTextEdit(self.formLayoutWidget)
        self.MGTnote.setObjectName("MGTnote")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.MGTnote)
        self.MGTpre = QtGui.QTextEdit(self.formLayoutWidget)
        self.MGTpre.setObjectName("MGTpre")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.MGTpre)
        self.MGLpre = QtGui.QLabel(self.formLayoutWidget)
        self.MGLpre.setObjectName("MGLpre")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.MGLpre)
        self.MGLpost = QtGui.QLabel(self.formLayoutWidget)
        self.MGLpost.setObjectName("MGLpost")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.MGLpost)
        self.MGTpost = QtGui.QTextEdit(self.formLayoutWidget)
        self.MGTpost.setObjectName("MGTpost")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.MGTpost)
        self.MachNB.addTab(self.MGT_2, "")
        self.MainTab.addTab(self.MachineTab, "")
        self.ToolsTab = QtGui.QWidget()
        self.ToolsTab.setObjectName("ToolsTab")
        self.ToolNameL = QtGui.QLabel(self.ToolsTab)
        self.ToolNameL.setGeometry(QtCore.QRect(10, 20, 82, 21))
        self.ToolNameL.setObjectName("ToolNameL")
        self.gridLayoutWidget = QtGui.QWidget(self.ToolsTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 331, 325))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.TGLDia = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLDia.setObjectName("TGLDia")
        self.gridLayout.addWidget(self.TGLDia, 2, 0, 1, 1)
        self.TGLRad = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLRad.setObjectName("TGLRad")
        self.gridLayout.addWidget(self.TGLRad, 3, 0, 1, 1)
        self.TGLTyp = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLTyp.setObjectName("TGLTyp")
        self.gridLayout.addWidget(self.TGLTyp, 1, 0, 1, 1)
        self.TGLFlu = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLFlu.setObjectName("TGLFlu")
        self.gridLayout.addWidget(self.TGLFlu, 7, 0, 1, 1)
        self.TGLLen = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLLen.setObjectName("TGLLen")
        self.gridLayout.addWidget(self.TGLLen, 4, 0, 1, 1)
        self.TGLCc = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLCc.setObjectName("TGLCc")
        self.gridLayout.addWidget(self.TGLCc, 8, 0, 1, 1)
        self.TGCBTyp = QtGui.QComboBox(self.gridLayoutWidget)
        self.TGCBTyp.setObjectName("TGCBTyp")
        self.gridLayout.addWidget(self.TGCBTyp, 1, 1, 1, 1)
        self.TGSPFlu = QtGui.QSpinBox(self.gridLayoutWidget)
        self.TGSPFlu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TGSPFlu.setReadOnly(True)
        self.TGSPFlu.setMaximum(12)
        self.TGSPFlu.setObjectName("TGSPFlu")
        self.gridLayout.addWidget(self.TGSPFlu, 7, 1, 1, 1)
        self.TGSPDia = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.TGSPDia.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TGSPDia.setReadOnly(True)
        self.TGSPDia.setDecimals(3)
        self.TGSPDia.setMaximum(999.99)
        self.TGSPDia.setSingleStep(0.005)
        self.TGSPDia.setObjectName("TGSPDia")
        self.gridLayout.addWidget(self.TGSPDia, 2, 1, 1, 1)
        self.TGSPRad = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.TGSPRad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TGSPRad.setReadOnly(True)
        self.TGSPRad.setDecimals(3)
        self.TGSPRad.setMaximum(999.99)
        self.TGSPRad.setSingleStep(0.005)
        self.TGSPRad.setObjectName("TGSPRad")
        self.gridLayout.addWidget(self.TGSPRad, 3, 1, 1, 1)
        self.TGSPLen = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.TGSPLen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TGSPLen.setReadOnly(True)
        self.TGSPLen.setDecimals(3)
        self.TGSPLen.setMaximum(999.99)
        self.TGSPLen.setSingleStep(0.005)
        self.TGSPLen.setObjectName("TGSPLen")
        self.gridLayout.addWidget(self.TGSPLen, 4, 1, 1, 1)
        self.TGCBCc = QtGui.QComboBox(self.gridLayoutWidget)
        self.TGCBCc.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.TGCBCc.setFont(font)
        self.TGCBCc.setEditable(False)
        self.TGCBCc.setObjectName("TGCBCc")
        self.gridLayout.addWidget(self.TGCBCc, 8, 1, 1, 1)
        self.TGLnote = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLnote.setObjectName("TGLnote")
        self.gridLayout.addWidget(self.TGLnote, 9, 0, 1, 1)
        self.TGTnote = QtGui.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TGTnote.sizePolicy().hasHeightForWidth())
        self.TGTnote.setSizePolicy(sizePolicy)
        self.TGTnote.setMinimumSize(QtCore.QSize(0, 0))
        self.TGTnote.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TGTnote.setObjectName("TGTnote")
        self.gridLayout.addWidget(self.TGTnote, 9, 1, 1, 1)
        self.TGLOvl = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLOvl.setObjectName("TGLOvl")
        self.gridLayout.addWidget(self.TGLOvl, 5, 0, 1, 1)
        self.TGSPOvl = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.TGSPOvl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TGSPOvl.setReadOnly(True)
        self.TGSPOvl.setDecimals(3)
        self.TGSPOvl.setMaximum(999.99)
        self.TGSPOvl.setSingleStep(0.005)
        self.TGSPOvl.setObjectName("TGSPOvl")
        self.gridLayout.addWidget(self.TGSPOvl, 5, 1, 1, 1)
        self.TGLShd = QtGui.QLabel(self.gridLayoutWidget)
        self.TGLShd.setObjectName("TGLShd")
        self.gridLayout.addWidget(self.TGLShd, 6, 0, 1, 1)
        self.TGSPShd = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.TGSPShd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TGSPShd.setReadOnly(True)
        self.TGSPShd.setDecimals(3)
        self.TGSPShd.setMaximum(999.99)
        self.TGSPShd.setSingleStep(0.005)
        self.TGSPShd.setObjectName("TGSPShd")
        self.gridLayout.addWidget(self.TGSPShd, 6, 1, 1, 1)
        self.ToolCB = QtGui.QComboBox(self.ToolsTab)
        self.ToolCB.setGeometry(QtCore.QRect(100, 20, 241, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToolCB.sizePolicy().hasHeightForWidth())
        self.ToolCB.setSizePolicy(sizePolicy)
        self.ToolCB.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.ToolCB.setObjectName("ToolCB")
        self.layoutWidget1 = QtGui.QWidget(self.ToolsTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 380, 331, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ToolNewPB = QtGui.QPushButton(self.layoutWidget1)
        self.ToolNewPB.setObjectName("ToolNewPB")
        self.horizontalLayout.addWidget(self.ToolNewPB)
        self.ToolDelPB = QtGui.QPushButton(self.layoutWidget1)
        self.ToolDelPB.setObjectName("ToolDelPB")
        self.horizontalLayout.addWidget(self.ToolDelPB)
        self.ToolModPB = QtGui.QPushButton(self.layoutWidget1)
        self.ToolModPB.setObjectName("ToolModPB")
        self.horizontalLayout.addWidget(self.ToolModPB)
        self.TTConf = QtGui.QPushButton(self.ToolsTab)
        self.TTConf.setEnabled(False)
        self.TTConf.setGeometry(QtCore.QRect(10, 410, 90, 26))
        self.TTConf.setObjectName("TTConf")
        self.MainTab.addTab(self.ToolsTab, "")
        self.WPTab = QtGui.QWidget()
        self.WPTab.setObjectName("WPTab")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.WPTab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 341, 318))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.WPGSBUDY = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.WPGSBUDY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WPGSBUDY.setDecimals(4)
        self.WPGSBUDY.setObjectName("WPGSBUDY")
        self.gridLayout_3.addWidget(self.WPGSBUDY, 3, 2, 1, 1)
        self.WPGLDX = QtGui.QLabel(self.gridLayoutWidget_3)
        self.WPGLDX.setObjectName("WPGLDX")
        self.gridLayout_3.addWidget(self.WPGLDX, 2, 0, 1, 1)
        self.WPGLMat = QtGui.QLabel(self.gridLayoutWidget_3)
        self.WPGLMat.setObjectName("WPGLMat")
        self.gridLayout_3.addWidget(self.WPGLMat, 0, 0, 1, 1)
        self.WPGLNote = QtGui.QLabel(self.gridLayoutWidget_3)
        self.WPGLNote.setObjectName("WPGLNote")
        self.gridLayout_3.addWidget(self.WPGLNote, 6, 0, 1, 1)
        self.WPGLDZ = QtGui.QLabel(self.gridLayoutWidget_3)
        self.WPGLDZ.setObjectName("WPGLDZ")
        self.gridLayout_3.addWidget(self.WPGLDZ, 4, 0, 1, 1)
        self.WPGSBLDY = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.WPGSBLDY.setObjectName("WPGSBLDY")
        self.gridLayout_3.addWidget(self.WPGSBLDY, 3, 1, 1, 1)
        self.WPGSBLDX = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.WPGSBLDX.setObjectName("WPGSBLDX")
        self.gridLayout_3.addWidget(self.WPGSBLDX, 2, 1, 1, 1)
        self.WPGSBUDZ = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.WPGSBUDZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WPGSBUDZ.setDecimals(4)
        self.WPGSBUDZ.setObjectName("WPGSBUDZ")
        self.gridLayout_3.addWidget(self.WPGSBUDZ, 4, 2, 1, 1)
        self.WPGLDY = QtGui.QLabel(self.gridLayoutWidget_3)
        self.WPGLDY.setObjectName("WPGLDY")
        self.gridLayout_3.addWidget(self.WPGLDY, 3, 0, 1, 1)
        self.WPGSBLDZ = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.WPGSBLDZ.setObjectName("WPGSBLDZ")
        self.gridLayout_3.addWidget(self.WPGSBLDZ, 4, 1, 1, 1)
        self.WPGSBUDX = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.WPGSBUDX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WPGSBUDX.setDecimals(4)
        self.WPGSBUDX.setObjectName("WPGSBUDX")
        self.gridLayout_3.addWidget(self.WPGSBUDX, 2, 2, 1, 1)
        self.WPGLlow = QtGui.QLabel(self.gridLayoutWidget_3)
        self.WPGLlow.setObjectName("WPGLlow")
        self.gridLayout_3.addWidget(self.WPGLlow, 1, 1, 1, 1)
        self.WPGLup = QtGui.QLabel(self.gridLayoutWidget_3)
        self.WPGLup.setObjectName("WPGLup")
        self.gridLayout_3.addWidget(self.WPGLup, 1, 2, 1, 1)
        self.WPGTNote = QtGui.QTextEdit(self.gridLayoutWidget_3)
        self.WPGTNote.setObjectName("WPGTNote")
        self.gridLayout_3.addWidget(self.WPGTNote, 6, 1, 1, 2)
        self.WPGCBMat = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.WPGCBMat.setObjectName("WPGCBMat")
        self.gridLayout_3.addWidget(self.WPGCBMat, 0, 1, 1, 2)
        self.layoutWidget_2 = QtGui.QWidget(self.WPTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 380, 341, 28))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.WPNewPB = QtGui.QPushButton(self.layoutWidget_2)
        self.WPNewPB.setObjectName("WPNewPB")
        self.horizontalLayout_4.addWidget(self.WPNewPB)
        self.WPModPB = QtGui.QPushButton(self.layoutWidget_2)
        self.WPModPB.setObjectName("WPModPB")
        self.horizontalLayout_4.addWidget(self.WPModPB)
        self.WPDelPB = QtGui.QPushButton(self.layoutWidget_2)
        self.WPDelPB.setObjectName("WPDelPB")
        self.horizontalLayout_4.addWidget(self.WPDelPB)
        self.WPCB = QtGui.QComboBox(self.WPTab)
        self.WPCB.setGeometry(QtCore.QRect(10, 10, 321, 25))
        self.WPCB.setObjectName("WPCB")
        self.WPConfPB = QtGui.QPushButton(self.WPTab)
        self.WPConfPB.setGeometry(QtCore.QRect(10, 410, 90, 26))
        self.WPConfPB.setObjectName("WPConfPB")
        self.MainTab.addTab(self.WPTab, "")
        self.ProcessTab = QtGui.QWidget()
        self.ProcessTab.setObjectName("ProcessTab")
        self.gridScrollWidget_4 = QtGui.QWidget(self.ProcessTab)
        self.gridScrollWidget_4.setGeometry(QtCore.QRect(10, 10, 342, 391))
        self.gridScrollWidget_4.setObjectName("gridScrollWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridScrollWidget_4)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.PCToolCB = QtGui.QComboBox(self.gridScrollWidget_4)
        self.PCToolCB.setObjectName("PCToolCB")
        self.gridLayout_4.addWidget(self.PCToolCB, 1, 1, 1, 1)
        self.PCMachL = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCMachL.setObjectName("PCMachL")
        self.gridLayout_4.addWidget(self.PCMachL, 0, 0, 1, 1)
        self.PCToolL = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCToolL.setObjectName("PCToolL")
        self.gridLayout_4.addWidget(self.PCToolL, 1, 0, 1, 1)
        self.PCMachCB = QtGui.QComboBox(self.gridScrollWidget_4)
        self.PCMachCB.setObjectName("PCMachCB")
        self.gridLayout_4.addWidget(self.PCMachCB, 0, 1, 1, 1)
        self.PCWPL = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCWPL.setObjectName("PCWPL")
        self.gridLayout_4.addWidget(self.PCWPL, 2, 0, 1, 1)
        self.PCWPCB = QtGui.QComboBox(self.gridScrollWidget_4)
        self.PCWPCB.setObjectName("PCWPCB")
        self.gridLayout_4.addWidget(self.PCWPCB, 2, 1, 1, 1)
        self.PCStrat = QtGui.QGroupBox(self.gridScrollWidget_4)
        self.PCStrat.setMaximumSize(QtCore.QSize(132, 126))
        self.PCStrat.setObjectName("PCStrat")
        self.verticalLayoutWidget = QtGui.QWidget(self.PCStrat)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 131, 100))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PCSTRB1 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.PCSTRB1.setMaximumSize(QtCore.QSize(128, 50))
        self.PCSTRB1.setObjectName("PCSTRB1")
        self.verticalLayout.addWidget(self.PCSTRB1)
        self.PCSTRB2 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.PCSTRB2.setMaximumSize(QtCore.QSize(128, 50))
        self.PCSTRB2.setObjectName("PCSTRB2")
        self.verticalLayout.addWidget(self.PCSTRB2)
        self.PCSTRB3 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.PCSTRB3.setMaximumSize(QtCore.QSize(128, 50))
        self.PCSTRB3.setObjectName("PCSTRB3")
        self.verticalLayout.addWidget(self.PCSTRB3)
        self.PCSTRB4 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.PCSTRB4.setMaximumSize(QtCore.QSize(128, 50))
        self.PCSTRB4.setObjectName("PCSTRB4")
        self.verticalLayout.addWidget(self.PCSTRB4)
        self.gridLayout_4.addWidget(self.PCStrat, 3, 0, 1, 1)
        self.PCPDir = QtGui.QGroupBox(self.gridScrollWidget_4)
        self.PCPDir.setObjectName("PCPDir")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.PCPDir)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 131, 100))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PCPDRB1 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.PCPDRB1.setObjectName("PCPDRB1")
        self.verticalLayout_2.addWidget(self.PCPDRB1)
        self.PCPDRB2 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.PCPDRB2.setObjectName("PCPDRB2")
        self.verticalLayout_2.addWidget(self.PCPDRB2)
        self.PCPDRB3 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.PCPDRB3.setObjectName("PCPDRB3")
        self.verticalLayout_2.addWidget(self.PCPDRB3)
        self.PCPDRB4 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.PCPDRB4.setObjectName("PCPDRB4")
        self.verticalLayout_2.addWidget(self.PCPDRB4)
        self.checkBox = QtGui.QCheckBox(self.PCPDir)
        self.checkBox.setGeometry(QtCore.QRect(0, 130, 121, 20))
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.PCPDir, 4, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.PCLXYovl = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCLXYovl.setObjectName("PCLXYovl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.PCLXYovl)
        self.PCSBXYovl = QtGui.QDoubleSpinBox(self.gridScrollWidget_4)
        self.PCSBXYovl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PCSBXYovl.setDecimals(4)
        self.PCSBXYovl.setMaximum(100.0)
        self.PCSBXYovl.setSingleStep(0.05)
        self.PCSBXYovl.setObjectName("PCSBXYovl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.PCSBXYovl)
        self.PCLZsd = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCLZsd.setObjectName("PCLZsd")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.PCLZsd)
        self.PCSBXYfc = QtGui.QDoubleSpinBox(self.gridScrollWidget_4)
        self.PCSBXYfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PCSBXYfc.setDecimals(4)
        self.PCSBXYfc.setMaximum(100.0)
        self.PCSBXYfc.setSingleStep(0.05)
        self.PCSBXYfc.setObjectName("PCSBXYfc")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.PCSBXYfc)
        self.PCLXYfc = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCLXYfc.setObjectName("PCLXYfc")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.PCLXYfc)
        self.PCSBZfc = QtGui.QDoubleSpinBox(self.gridScrollWidget_4)
        self.PCSBZfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PCSBZfc.setDecimals(4)
        self.PCSBZfc.setMaximum(100.0)
        self.PCSBZfc.setSingleStep(0.05)
        self.PCSBZfc.setObjectName("PCSBZfc")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.PCSBZfc)
        self.PCLZfc = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCLZfc.setObjectName("PCLZfc")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.PCLZfc)
        self.PCSB01 = QtGui.QDoubleSpinBox(self.gridScrollWidget_4)
        self.PCSB01.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PCSB01.setDecimals(4)
        self.PCSB01.setMaximum(100.0)
        self.PCSB01.setSingleStep(0.05)
        self.PCSB01.setObjectName("PCSB01")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.PCSB01)
        self.PCL01 = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCL01.setObjectName("PCL01")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.PCL01)
        self.PCLTd = QtGui.QLabel(self.gridScrollWidget_4)
        self.PCLTd.setObjectName("PCLTd")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.PCLTd)
        self.PCTTd = QtGui.QLineEdit(self.gridScrollWidget_4)
        self.PCTTd.setObjectName("PCTTd")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.PCTTd)
        self.PCSBZsd = QtGui.QDoubleSpinBox(self.gridScrollWidget_4)
        self.PCSBZsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PCSBZsd.setDecimals(4)
        self.PCSBZsd.setMaximum(100.0)
        self.PCSBZsd.setSingleStep(0.05)
        self.PCSBZsd.setObjectName("PCSBZsd")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.PCSBZsd)
        self.gridLayout_4.addLayout(self.formLayout, 3, 1, 2, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.ProcessTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 410, 341, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PCPBCal = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.PCPBCal.setObjectName("PCPBCal")
        self.horizontalLayout_5.addWidget(self.PCPBCal)
        self.PCPBGenG = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.PCPBGenG.setObjectName("PCPBGenG")
        self.horizontalLayout_5.addWidget(self.PCPBGenG)
        self.PCPBCt = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.PCPBCt.setObjectName("PCPBCt")
        self.horizontalLayout_5.addWidget(self.PCPBCt)
        self.MainTab.addTab(self.ProcessTab, "")
        self.GCodeTab = QtGui.QWidget()
        self.GCodeTab.setObjectName("GCodeTab")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.GCodeTab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 341, 371))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.GCmodel = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.GCmodel.setObjectName("GCmodel")
        self.gridLayout_6.addWidget(self.GCmodel, 2, 0, 1, 1)
        self.GCmachine = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.GCmachine.setObjectName("GCmachine")
        self.gridLayout_6.addWidget(self.GCmachine, 3, 0, 1, 1)
        self.GCtp = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.GCtp.setObjectName("GCtp")
        self.gridLayout_6.addWidget(self.GCtp, 6, 0, 1, 1)
        self.GCtool = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.GCtool.setObjectName("GCtool")
        self.gridLayout_6.addWidget(self.GCtool, 4, 0, 1, 1)
        self.GCwp = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.GCwp.setObjectName("GCwp")
        self.gridLayout_6.addWidget(self.GCwp, 5, 0, 1, 1)
        self.GCverbose = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.GCverbose.setObjectName("GCverbose")
        self.gridLayout_6.addWidget(self.GCverbose, 8, 0, 1, 1)
        self.GCSBd = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.GCSBd.setMinimum(2)
        self.GCSBd.setMaximum(5)
        self.GCSBd.setProperty("value", 4)
        self.GCSBd.setObjectName("GCSBd")
        self.gridLayout_6.addWidget(self.GCSBd, 7, 1, 1, 1)
        self.GCview = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.GCview.setObjectName("GCview")
        self.gridLayout_6.addWidget(self.GCview, 9, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_4.setIndent(25)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 7, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.GCodeTab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 390, 341, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.GCPB1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.GCPB1.setObjectName("GCPB1")
        self.horizontalLayout_6.addWidget(self.GCPB1)
        self.GCPB2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.GCPB2.setObjectName("GCPB2")
        self.horizontalLayout_6.addWidget(self.GCPB2)
        self.GCPB3 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.GCPB3.setObjectName("GCPB3")
        self.horizontalLayout_6.addWidget(self.GCPB3)
        self.MainTab.addTab(self.GCodeTab, "")
        self.TaskTab = QtGui.QWidget()
        self.TaskTab.setObjectName("TaskTab")
        self.MainTab.addTab(self.TaskTab, "")
        self.horizontalWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(5, 0, 760, 29))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.IL_1 = QtGui.QLabel(self.horizontalWidget)
        self.IL_1.setFrameShape(QtGui.QFrame.Panel)
        self.IL_1.setFrameShadow(QtGui.QFrame.Raised)
        self.IL_1.setLineWidth(1)
        self.IL_1.setObjectName("IL_1")
        self.horizontalLayout_3.addWidget(self.IL_1)
        self.IL_2 = QtGui.QLabel(self.horizontalWidget)
        self.IL_2.setFrameShape(QtGui.QFrame.Panel)
        self.IL_2.setFrameShadow(QtGui.QFrame.Raised)
        self.IL_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IL_2.setObjectName("IL_2")
        self.horizontalLayout_3.addWidget(self.IL_2)
        self.IL_3 = QtGui.QLabel(self.horizontalWidget)
        self.IL_3.setFrameShape(QtGui.QFrame.Panel)
        self.IL_3.setFrameShadow(QtGui.QFrame.Raised)
        self.IL_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IL_3.setObjectName("IL_3")
        self.horizontalLayout_3.addWidget(self.IL_3)
        self.IL_4 = QtGui.QLabel(self.horizontalWidget)
        self.IL_4.setFrameShape(QtGui.QFrame.Panel)
        self.IL_4.setFrameShadow(QtGui.QFrame.Raised)
        self.IL_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IL_4.setObjectName("IL_4")
        self.horizontalLayout_3.addWidget(self.IL_4)
        self.IL_5 = QtGui.QLabel(self.horizontalWidget)
        self.IL_5.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.IL_5.setFrameShape(QtGui.QFrame.Panel)
        self.IL_5.setFrameShadow(QtGui.QFrame.Raised)
        self.IL_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IL_5.setObjectName("IL_5")
        self.horizontalLayout_3.addWidget(self.IL_5)
        self.Log = QtGui.QTextEdit(self.centralwidget)
        self.Log.setGeometry(QtCore.QRect(10, 540, 751, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Log.sizePolicy().hasHeightForWidth())
        self.Log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Log.setFont(font)
        self.Log.setProperty("cursor", QtCore.Qt.BlankCursor)
        self.Log.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Log.setTabStopWidth(5)
        self.Log.setObjectName("Log")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(365, 34, 20, 491))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 520, 981, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(5, 34, 760, 3))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.RightTB = QtGui.QToolBox(self.centralwidget)
        self.RightTB.setGeometry(QtCore.QRect(380, 40, 381, 471))
        self.RightTB.setObjectName("RightTB")
        self.GWid = QtGui.QWidget()
        self.GWid.setGeometry(QtCore.QRect(0, 0, 381, 413))
        self.GWid.setObjectName("GWid")
        self.GV = QtGui.QGraphicsView(self.GWid)
        self.GV.setGeometry(QtCore.QRect(0, 0, 381, 421))
        self.GV.setObjectName("GV")
        self.RightTB.addItem(self.GWid, "")
        self.TAL = QtGui.QWidget()
        self.TAL.setGeometry(QtCore.QRect(0, 0, 381, 413))
        self.TAL.setObjectName("TAL")
        self.TWid = QtGui.QTextBrowser(self.TAL)
        self.TWid.setGeometry(QtCore.QRect(0, 0, 381, 431))
        self.TWid.setObjectName("TWid")
        self.RightTB.addItem(self.TAL, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.MenuShow = QtGui.QMenu(self.menubar)
        self.MenuShow.setObjectName("MenuShow")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Drawing = QtGui.QAction(MainWindow)
        self.actionOpen_Drawing.setObjectName("actionOpen_Drawing")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_EuroCAM = QtGui.QAction(MainWindow)
        self.actionAbout_EuroCAM.setObjectName("actionAbout_EuroCAM")
        self.menuInch = QtGui.QAction(MainWindow)
        self.menuInch.setCheckable(True)
        self.menuInch.setObjectName("menuInch")
        self.actionGCF = QtGui.QAction(MainWindow)
        self.actionGCF.setObjectName("actionGCF")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionShow_display_window = QtGui.QAction(MainWindow)
        self.actionShow_display_window.setObjectName("actionShow_display_window")
        self.menuFile.addAction(self.actionOpen_Drawing)
        self.menuFile.addAction(self.actionExit)
        self.menuConfiguration.addSeparator()
        self.menuConfiguration.addAction(self.menuInch)
        self.menuConfiguration.addAction(self.actionGCF)
        self.MenuShow.addAction(self.actionShow_display_window)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout_EuroCAM)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.MenuShow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.MainTab.setCurrentIndex(5)
        self.MachNB.setCurrentIndex(0)
        self.RightTB.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "EuroCAM", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLName.setText(QtGui.QApplication.translate("MainWindow", "Model Name", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLmax.setText(QtGui.QApplication.translate("MainWindow", "max", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLZ.setText(QtGui.QApplication.translate("MainWindow", "Model Z", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLX.setText(QtGui.QApplication.translate("MainWindow", "Model X", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLY.setText(QtGui.QApplication.translate("MainWindow", "Model Y", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLmin.setText(QtGui.QApplication.translate("MainWindow", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLdimx.setText(QtGui.QApplication.translate("MainWindow", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLdimz.setText(QtGui.QApplication.translate("MainWindow", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.MdLdimy.setText(QtGui.QApplication.translate("MainWindow", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTab.setTabText(self.MainTab.indexOf(self.ModelTab), QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Machine Name", None, QtGui.QApplication.UnicodeUTF8))
        self.MachNewPB.setText(QtGui.QApplication.translate("MainWindow", "New Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.MachModPB.setText(QtGui.QApplication.translate("MainWindow", "Modify Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.MachDelPB.setText(QtGui.QApplication.translate("MainWindow", "Delete Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.MachConfPB.setText(QtGui.QApplication.translate("MainWindow", "Confirm", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLFX.setText(QtGui.QApplication.translate("MainWindow", "Max FeedRate X", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLFY.setText(QtGui.QApplication.translate("MainWindow", "Max FeedRate Y", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLTX.setText(QtGui.QApplication.translate("MainWindow", "Max Travel X", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLTY.setText(QtGui.QApplication.translate("MainWindow", "Max Travel Y", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLTZ.setText(QtGui.QApplication.translate("MainWindow", "Max Travel Z", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLFZ.setText(QtGui.QApplication.translate("MainWindow", "Max FeedRate Z", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLCo.setText(QtGui.QApplication.translate("MainWindow", "Coordinates", None, QtGui.QApplication.UnicodeUTF8))
        self.MachNB.setTabText(self.MachNB.indexOf(self.MGT_1), QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLnote.setText(QtGui.QApplication.translate("MainWindow", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLpre.setText(QtGui.QApplication.translate("MainWindow", "Preamble", None, QtGui.QApplication.UnicodeUTF8))
        self.MGLpost.setText(QtGui.QApplication.translate("MainWindow", "PostAmble", None, QtGui.QApplication.UnicodeUTF8))
        self.MachNB.setTabText(self.MachNB.indexOf(self.MGT_2), QtGui.QApplication.translate("MainWindow", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTab.setTabText(self.MainTab.indexOf(self.MachineTab), QtGui.QApplication.translate("MainWindow", "Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolNameL.setText(QtGui.QApplication.translate("MainWindow", "Tool Name", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLDia.setText(QtGui.QApplication.translate("MainWindow", "Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLRad.setText(QtGui.QApplication.translate("MainWindow", "Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLTyp.setText(QtGui.QApplication.translate("MainWindow", "Tool Type", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLFlu.setText(QtGui.QApplication.translate("MainWindow", "Flutes", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLLen.setText(QtGui.QApplication.translate("MainWindow", "Cutter Length", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLCc.setText(QtGui.QApplication.translate("MainWindow", "Center Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLnote.setText(QtGui.QApplication.translate("MainWindow", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLOvl.setText(QtGui.QApplication.translate("MainWindow", "Overall Length", None, QtGui.QApplication.UnicodeUTF8))
        self.TGLShd.setText(QtGui.QApplication.translate("MainWindow", "Shaft Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolNewPB.setText(QtGui.QApplication.translate("MainWindow", "New Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolDelPB.setText(QtGui.QApplication.translate("MainWindow", "Delete Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolModPB.setText(QtGui.QApplication.translate("MainWindow", "Modify Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.TTConf.setText(QtGui.QApplication.translate("MainWindow", "Confirm", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTab.setTabText(self.MainTab.indexOf(self.ToolsTab), QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.WPGLDX.setText(QtGui.QApplication.translate("MainWindow", "Dim X", None, QtGui.QApplication.UnicodeUTF8))
        self.WPGLMat.setText(QtGui.QApplication.translate("MainWindow", "Material", None, QtGui.QApplication.UnicodeUTF8))
        self.WPGLNote.setText(QtGui.QApplication.translate("MainWindow", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.WPGLDZ.setText(QtGui.QApplication.translate("MainWindow", "Dim Z", None, QtGui.QApplication.UnicodeUTF8))
        self.WPGLDY.setText(QtGui.QApplication.translate("MainWindow", "Dim Y", None, QtGui.QApplication.UnicodeUTF8))
        self.WPGLlow.setText(QtGui.QApplication.translate("MainWindow", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.WPGLup.setText(QtGui.QApplication.translate("MainWindow", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        self.WPNewPB.setText(QtGui.QApplication.translate("MainWindow", "New WP", None, QtGui.QApplication.UnicodeUTF8))
        self.WPModPB.setText(QtGui.QApplication.translate("MainWindow", "Modify WP", None, QtGui.QApplication.UnicodeUTF8))
        self.WPDelPB.setText(QtGui.QApplication.translate("MainWindow", "Delete WP", None, QtGui.QApplication.UnicodeUTF8))
        self.WPConfPB.setText(QtGui.QApplication.translate("MainWindow", "Confirm", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTab.setTabText(self.MainTab.indexOf(self.WPTab), QtGui.QApplication.translate("MainWindow", "WorkPiece", None, QtGui.QApplication.UnicodeUTF8))
        self.ProcessTab.setAccessibleName(QtGui.QApplication.translate("MainWindow", "Azioni", None, QtGui.QApplication.UnicodeUTF8))
        self.PCMachL.setText(QtGui.QApplication.translate("MainWindow", "Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.PCToolL.setText(QtGui.QApplication.translate("MainWindow", "Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.PCWPL.setText(QtGui.QApplication.translate("MainWindow", "WorkPiece", None, QtGui.QApplication.UnicodeUTF8))
        self.PCStrat.setTitle(QtGui.QApplication.translate("MainWindow", "Path Strategy", None, QtGui.QApplication.UnicodeUTF8))
        self.PCSTRB1.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Make various passes in the direction selected stepping down on every passes by an amount calculated from the height of the workpiece and the diameter of the tool choosen, this calculated amount could be adjusted using the Step Down Correction (100 = calculated amount, -90 10% less amount 110 10% plus amount)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.PCSTRB1.setText(QtGui.QApplication.translate("MainWindow", "Slice Removal", None, QtGui.QApplication.UnicodeUTF8))
        self.PCSTRB2.setText(QtGui.QApplication.translate("MainWindow", "Countour", None, QtGui.QApplication.UnicodeUTF8))
        self.PCSTRB3.setText(QtGui.QApplication.translate("MainWindow", "Engraving", None, QtGui.QApplication.UnicodeUTF8))
        self.PCSTRB4.setText(QtGui.QApplication.translate("MainWindow", "Laser Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.PCPDir.setTitle(QtGui.QApplication.translate("MainWindow", "Path Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.PCPDRB1.setText(QtGui.QApplication.translate("MainWindow", "X Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.PCPDRB2.setText(QtGui.QApplication.translate("MainWindow", "Y Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.PCPDRB3.setText(QtGui.QApplication.translate("MainWindow", "Diagonal \\", None, QtGui.QApplication.UnicodeUTF8))
        self.PCPDRB4.setText(QtGui.QApplication.translate("MainWindow", "Diagonal /", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Bi Dir. Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.PCLXYovl.setText(QtGui.QApplication.translate("MainWindow", "X Y Pass Incr", None, QtGui.QApplication.UnicodeUTF8))
        self.PCLZsd.setText(QtGui.QApplication.translate("MainWindow", "Z Step Down", None, QtGui.QApplication.UnicodeUTF8))
        self.PCLXYfc.setText(QtGui.QApplication.translate("MainWindow", "X Y Feedrate", None, QtGui.QApplication.UnicodeUTF8))
        self.PCLZfc.setText(QtGui.QApplication.translate("MainWindow", "Z Plungerate", None, QtGui.QApplication.UnicodeUTF8))
        self.PCL01.setText(QtGui.QApplication.translate("MainWindow", "Text Label 01", None, QtGui.QApplication.UnicodeUTF8))
        self.PCLTd.setText(QtGui.QApplication.translate("MainWindow", "Tool Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.PCPBCal.setText(QtGui.QApplication.translate("MainWindow", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.PCPBGenG.setText(QtGui.QApplication.translate("MainWindow", "G-Code Gen", None, QtGui.QApplication.UnicodeUTF8))
        self.PCPBCt.setText(QtGui.QApplication.translate("MainWindow", "Create Task", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTab.setTabText(self.MainTab.indexOf(self.ProcessTab), QtGui.QApplication.translate("MainWindow", "Processes", None, QtGui.QApplication.UnicodeUTF8))
        self.GCmodel.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>If checked it insert in the G-Code file at the beginning a comment containing:</p><p>- model name</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.GCmodel.setText(QtGui.QApplication.translate("MainWindow", "Model data ", None, QtGui.QApplication.UnicodeUTF8))
        self.GCmachine.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>If checked it insert in the G-Code file at the beginning a comment containing:</p><p><br/></p><p>- Machine name</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.GCmachine.setText(QtGui.QApplication.translate("MainWindow", "Machine data", None, QtGui.QApplication.UnicodeUTF8))
        self.GCtp.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>If checked it insert in the G-Code file at the beginning a comment containing:</p><p><br/></p><p>- Strategy</p><p>- Direction</p><p>- Number of slice / Number of slices generated</p><p>- Slice height </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.GCtp.setText(QtGui.QApplication.translate("MainWindow", "Tool Path data", None, QtGui.QApplication.UnicodeUTF8))
        self.GCtool.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>If checked it insert in the G-Code file at the beginning a comment containing:</p><p><br/></p><p>- Tool Name</p><p>- Tool shape</p><p>- Tool Diameter</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.GCtool.setText(QtGui.QApplication.translate("MainWindow", "Tool Data", None, QtGui.QApplication.UnicodeUTF8))
        self.GCwp.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>If checked it insert in the G-Code file at the beginning a comment containing:</p><p><br/></p><p>- Work Piece dimensions</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.GCwp.setText(QtGui.QApplication.translate("MainWindow", "WorkPiece data", None, QtGui.QApplication.UnicodeUTF8))
        self.GCverbose.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Insert into the code some comment :</p><p><br/></p><p>- at the end of the preamble</p><p>- at the end of the postamble</p><p>- at the end of the pass in the path</p><p>- when the tool is raised a the safe height</p><p><br/></p><p><br/></p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.GCverbose.setText(QtGui.QApplication.translate("MainWindow", "Verbose comment", None, QtGui.QApplication.UnicodeUTF8))
        self.GCview.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Diplay the generated Tool Path at the end of each Tool Path generation, close the window when you have done to generate the next Tool Path</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.GCview.setText(QtGui.QApplication.translate("MainWindow", "View the generated Tool Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Number of decimals ", None, QtGui.QApplication.UnicodeUTF8))
        self.GCPB1.setText(QtGui.QApplication.translate("MainWindow", "Gen. G-Code", None, QtGui.QApplication.UnicodeUTF8))
        self.GCPB2.setText(QtGui.QApplication.translate("MainWindow", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.GCPB3.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTab.setTabText(self.MainTab.indexOf(self.GCodeTab), QtGui.QApplication.translate("MainWindow", "G-Code", None, QtGui.QApplication.UnicodeUTF8))
        self.MainTab.setTabText(self.MainTab.indexOf(self.TaskTab), QtGui.QApplication.translate("MainWindow", "Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.IL_1.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.IL_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.IL_3.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.IL_4.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.IL_5.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.RightTB.setItemText(self.RightTB.indexOf(self.GWid), QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.RightTB.setItemText(self.RightTB.indexOf(self.TAL), QtGui.QApplication.translate("MainWindow", "TextBox", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfiguration.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.MenuShow.setTitle(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Drawing.setText(QtGui.QApplication.translate("MainWindow", "Open Drawing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_EuroCAM.setText(QtGui.QApplication.translate("MainWindow", "About EuroCAM", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInch.setText(QtGui.QApplication.translate("MainWindow", "Unit inch", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInch.setToolTip(QtGui.QApplication.translate("MainWindow", "Unit inch (checked is inch)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGCF.setText(QtGui.QApplication.translate("MainWindow", "G code filename", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_display_window.setText(QtGui.QApplication.translate("MainWindow", "Show display window", None, QtGui.QApplication.UnicodeUTF8))

